
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 09 11:53:00 CEST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int MOD = 12;
  public static final int AND = 19;
  public static final int IMPL = 22;
  public static final int LT = 15;
  public static final int PLUS = 4;
  public static final int OR = 20;
  public static final int NOT = 21;
  public static final int QUEST = 24;
  public static final int TRUE = 10;
  public static final int COLON = 25;
  public static final int GT = 17;
  public static final int LE = 16;
  public static final int SEMIC = 9;
  public static final int EOF = 0;
  public static final int MINUS_U = 8;
  public static final int MULT = 6;
  public static final int DIV = 7;
  public static final int EQUIV = 23;
  public static final int GE = 18;
  public static final int FALSE = 11;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int COMPLEX = 28;
  public static final int INTEGER = 26;
  public static final int RPAR = 3;
  public static final int DIFF = 14;
  public static final int REAL = 27;
  public static final int LPAR = 2;
}

