
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 20 11:26:13 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompilerSymbol {
  /* terminals */
  public static final int OP = 4;
  public static final int ID = 3;
  public static final int NUM = 2;
  public static final int error = 1;
  public static final int NUMBER = 7;
  public static final int LPAR = 5;
  public static final int RPAR = 6;
  public static final int EOF = 0;
}

