
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 02 16:07:53 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompilerSymbol {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int CHAR = 35;
  public static final int UINT = 32;
  public static final int SEMIC = 11;
  public static final int INT = 31;
  public static final int MINUS = 7;
  public static final int NOT = 26;
  public static final int AND = 12;
  public static final int RPAR = 3;
  public static final int INF = 16;
  public static final int OR = 13;
  public static final int BOOL = 34;
  public static final int INFE = 17;
  public static final int TAB = 23;
  public static final int AFFECT = 20;
  public static final int SUPE = 19;
  public static final int PLUS = 6;
  public static final int EOF = 0;
  public static final int EQUAL = 14;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int NUMBER = 30;
  public static final int MOD = 25;
  public static final int INDTAB = 24;
  public static final int TIMES = 8;
  public static final int LPARTAB = 4;
  public static final int RPARTAB = 5;
  public static final int PROP = 27;
  public static final int FLOAT = 33;
  public static final int SUP = 18;
  public static final int LPAR = 2;
  public static final int DIFF = 15;
  public static final int MINUS_U = 10;
  public static final int CHAINE = 28;
  public static final int FALSE = 22;
  public static final int VAR = 29;
}

